In [2]:
import pandas as pd

ventas_df = pd.read_csv(
    "../data/ventas.csv"
)

ventas_df["importe"] = ventas_df["unidades"] * ventas_df["precio_unitario"]
ventas_df.head(5)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,importe
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0,650
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0,4480
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0,280
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0,12000
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1,260

In [3]:
# Forma permitida pero muy lenta
ventas_df[ventas_df["region"] == "Sur"]["importe"].sum()

np.int64(699920)

In [5]:
ventas_df.groupby("region")["importe"].sum()

region
Centro    705695
Este      549745
Norte     862360
Oeste     626295
Sur       699920
Name: importe, dtype: int64

In [6]:
ventas_df[ventas_df["region"] == "Sur"]["importe"].mean()

np.float64(2916.3333333333335)

In [7]:
ventas_df.groupby("region")["importe"].mean()

region
Centro    2594.466912
Este      3054.138889
Norte     2827.409836
Oeste     3085.197044
Sur       2916.333333
Name: importe, dtype: float64

In [8]:
ventas_df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

#### Adicionando más stats a mi función agregada

In [9]:
ventas_df.groupby("region")["importe"].agg(["sum", "mean", "median", "count"])

           sum         mean  median  count
region
Centro  705695  2594.466912  1580.0    272
Este    549745  3054.138889  1740.0    180
Norte   862360  2827.409836  1400.0    305
Oeste   626295  3085.197044  1820.0    203
Sur     699920  2916.333333  1340.0    240

#### Agregando alias a mis operaciones agregadas

In [10]:
ventas_df.groupby("region")["importe"].agg(
    importe_total="sum",
    importe_promedio="mean",
    importe_mediana="median",
    cantidad_registros="count"
)

        importe_total  importe_promedio  importe_mediana  cantidad_registros
region
Centro         705695       2594.466912           1580.0                 272
Este           549745       3054.138889           1740.0                 180
Norte          862360       2827.409836           1400.0                 305
Oeste          626295       3085.197044           1820.0                 203
Sur            699920       2916.333333           1340.0                 240

#### Agrupar por n-columnas

In [11]:
ventas_df.groupby(["region", "categoria"])["importe"].agg(
    importe_total="sum",
    importe_promedio="mean",
    total_registros="count"
)

                   importe_total  importe_promedio  total_registros
region categoria
Centro Accesorios          56895        605.265957               94
       Mobiliario         201520       2651.578947               76
       Tecnologia         447280       4385.098039              102
Este   Accesorios          44585        675.530303               66
       Mobiliario         136520       2730.400000               50
       Tecnologia         368640       5760.000000               64
Norte  Accesorios          78630        639.268293              123
       Mobiliario         200130       2668.400000               75
       Tecnologia         583600       5454.205607              107
Oeste  Accesorios          40205        628.203125               64
       Mobiliario         156170       2692.586207               58
       Tecnologia         429920       5307.654321               81
Sur    Accesorios          57800        642.222222               90
       Mobiliario         155320       2724.912281               57
       Tecnologia         486800       5234.408602               93

In [12]:
ventas_df.groupby("region").agg({
    "importe": ["sum", "mean", "max"],
    "unidades": ["sum"],
    "producto": ["nunique"]
})

       importe                     unidades producto
           sum         mean    max      sum  nunique
region
Centro  705695  2594.466912  15600     1933        8
Este    549745  3054.138889  16800     1384        8
Norte   862360  2827.409836  16800     2166        8
Oeste   626295  3085.197044  15600     1469        8
Sur     699920  2916.333333  16800     1779        8

In [13]:
ventas_df.groupby(["region", "categoria", "vendedor"]).agg({
    "importe": ["sum", "mean", "max"],
    "unidades": ["sum"],
    "producto": ["nunique"]
})

                              importe                     unidades producto
                                  sum         mean    max      sum  nunique
region categoria  vendedor
Centro Accesorios Ana Torres     4100   341.666667    910       76        2
                  Carlos Vega    5150   468.181818   1560       68        3
                  Elena Mora     7035   703.500000   1820       87        3
                  Javier Sanz    7500   681.818182   1820       68        3
                  Luis Gomez     5205   578.333333   1235       71        3
...                               ...          ...    ...      ...      ...
Sur    Tecnologia Javier Sanz   62000  5166.666667  13200       94        3
                  Luis Gomez    73760  8195.555556  16800      101        3
                  Marta Ruiz    24400  3050.000000   8400       50        3
                  Pedro Diaz    24640  3080.000000   7680       49        2
                  Sofia Leon    96720  6448.000000  16800      123        3

[120 rows x 5 columns]

In [16]:
ventas_df.groupby("fecha")["importe"].agg(["sum", "count"])

              sum  count
fecha
2024-01-02  17410      4
2024-01-03   4660      6
2024-01-04   6740      3
2024-01-05   2570      2
2024-01-06  29220      5
...           ...    ...
2024-12-27   4500      1
2024-12-28  12200      4
2024-12-29   1980      2
2024-12-30  20255      6
2024-12-31   2920      3

[349 rows x 2 columns]

In [18]:
ventas_df[ventas_df["fecha"] == "2024-01-02"]["importe"].sum()

np.int64(17410)

In [17]:
ventas_df[ventas_df["fecha"] == "2024-01-02"]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,importe
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0,650
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0,4480
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0,280
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0,12000