### Concatenado de tablas

In [2]:
import pandas as pd

enero = pd.DataFrame({
    "mes": ["Enero"],
    "numero_mes": [1]
})

febrero = pd.DataFrame({
    "mes": ["Febrero"],
    "numero_mes": [2]
})

marzo = pd.DataFrame({
    "mes": ["Marzo"],
    "numero_mes": [3]
})

In [15]:
febrero

       mes  numero_mes
0  Febrero           2

In [4]:
### Concatenar por columnas
pd.concat([enero, febrero, marzo], axis=1)

     mes  numero_mes      mes  numero_mes    mes  numero_mes
0  Enero           1  Febrero           2  Marzo           3

In [5]:
### Concatenar por filas
pd.concat([enero, febrero, marzo], axis=0)

       mes  numero_mes
0    Enero           1
0  Febrero           2
0    Marzo           3

In [16]:
pd.concat([enero, febrero, marzo], axis=0).reset_index()

   index      mes  numero_mes
0      0    Enero           1
1      0  Febrero           2
2      0    Marzo           3

In [6]:
### Concatenar por filas y resetear índices
pd.concat([enero, febrero, marzo], axis=0).reset_index(drop=True)

       mes  numero_mes
0    Enero           1
1  Febrero           2
2    Marzo           3

### JOINS

In [7]:
ventas_df = pd.read_csv("../data/ventas.csv")
catalogo_productos_df = pd.read_csv("../data/catalogo_productos.csv")

In [8]:
ventas_df.head(5)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [9]:
catalogo_productos_df.head(10)

      producto  coste_unitario proveedor  stock
0   Laptop Pro             780  TecnoSur     45
1   Monitor 27             195  TecnoSur    120
2  Teclado Mec              52   InputCo    300
3   Raton Ergo              21   InputCo    500
4   Silla Ergo             160   ErgoLab     80
5   Escritorio             250   ErgoLab     35
6  Auriculares              68   InputCo    210
7   Tablet Air             390  TecnoSur     60

#### LEFT JOIN

In [10]:
ventas_df.shape

(1200, 8)

In [11]:
left_join = ventas_df.merge(catalogo_productos_df, on="producto", how="left")
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68,InputCo,210
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195,TecnoSur,120
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160,ErgoLab,80
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780,TecnoSur,45
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68,InputCo,210
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21,InputCo,500
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780,TecnoSur,45
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195,TecnoSur,120
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195,TecnoSur,120
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00,21,InputCo,500

In [12]:
ventas_df.loc[1199, "producto"] = "Monitor 32"
ventas_df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Monitor 32,Accesorios,8,45,0.00

In [13]:
left_join = ventas_df.merge(catalogo_productos_df, on="producto", how="left")
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68.0,InputCo,210.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195.0,TecnoSur,120.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160.0,ErgoLab,80.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780.0,TecnoSur,45.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68.0,InputCo,210.0
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21.0,InputCo,500.0
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780.0,TecnoSur,45.0
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195.0,TecnoSur,120.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195.0,TecnoSur,120.0
1199,2024-12-31,Norte,Marta Ruiz,Monitor 32,Accesorios,8,45,0.00,NaN,NaN,NaN

### INNER JOIN

In [14]:
inner_join = ventas_df.merge(catalogo_productos_df, on="producto", how="inner")
inner_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68,InputCo,210
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195,TecnoSur,120
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160,ErgoLab,80
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780,TecnoSur,45
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68,InputCo,210
...,...,...,...,...,...,...,...,...,...,...,...
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.00,390,TecnoSur,60
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21,InputCo,500
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780,TecnoSur,45
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195,TecnoSur,120
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195,TecnoSur,120

### RIGHT JOIN

In [21]:
nueva_fila = pd.DataFrame([{
    "producto": "iPhone 18 Pro Max",
    "coste_unitario": 1000,
    "proveedor": "Apple",
    "stock": 250
}])
nueva_fila

            producto  coste_unitario proveedor  stock
0  iPhone 18 Pro Max            1000     Apple    250

In [22]:
catalogo_productos_df = pd.concat([catalogo_productos_df, nueva_fila], axis=0).reset_index(drop=True)
catalogo_productos_df

            producto  coste_unitario proveedor  stock
0         Laptop Pro             780  TecnoSur     45
1         Monitor 27             195  TecnoSur    120
2        Teclado Mec              52   InputCo    300
3         Raton Ergo              21   InputCo    500
4         Silla Ergo             160   ErgoLab     80
5         Escritorio             250   ErgoLab     35
6        Auriculares              68   InputCo    210
7         Tablet Air             390  TecnoSur     60
8  iPhone 18 Pro Max            1000     Apple    250

In [23]:
right_join = ventas_df.merge(catalogo_productos_df, on="producto", how="right")
right_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10.0,1200.0,0.0,780,TecnoSur,45
1,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1.0,1200.0,0.1,780,TecnoSur,45
2,2024-01-06,Oeste,Pedro Diaz,Laptop Pro,Tecnologia,8.0,1200.0,0.0,780,TecnoSur,45
3,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13.0,1200.0,0.0,780,TecnoSur,45
4,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1.0,1200.0,0.0,780,TecnoSur,45
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-24,Este,Elena Mora,Tablet Air,Tecnologia,5.0,640.0,0.0,390,TecnoSur,60
1196,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14.0,640.0,0.0,390,TecnoSur,60
1197,2024-12-28,Este,Luis Gomez,Tablet Air,Tecnologia,13.0,640.0,0.0,390,TecnoSur,60
1198,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4.0,640.0,0.0,390,TecnoSur,60
1199,NaN,NaN,NaN,iPhone 18 Pro Max,NaN,NaN,NaN,NaN,1000,Apple,250

### LEFT ANTI JOIN

In [24]:
left_anti_join = ventas_df.merge(catalogo_productos_df, on="producto", how="left_anti")
left_anti_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
1199,2024-12-31,Norte,Marta Ruiz,Monitor 32,Accesorios,8,45,0.0,NaN,NaN,NaN

### RIGHT ANTI JOIN

In [ ]:
right_anti_join = ventas_df.merge(catalogo_productos_df, on="producto", how="right_anti")
right_anti_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
1199,NaN,NaN,NaN,iPhone 18 Pro Max,NaN,NaN,NaN,NaN,1000,Apple,250

### CROSS JOIN

In [28]:
cross_join = catalogo_productos_df.merge(catalogo_productos_df, how="cross")
cross_join.head(50)

,producto_x,coste_unitario_x,proveedor_x,stock_x,producto_y,coste_unitario_y,proveedor_y,stock_y
0,Laptop Pro,780,TecnoSur,45,Laptop Pro,780,TecnoSur,45
1,Laptop Pro,780,TecnoSur,45,Monitor 27,195,TecnoSur,120
2,Laptop Pro,780,TecnoSur,45,Teclado Mec,52,InputCo,300
3,Laptop Pro,780,TecnoSur,45,Raton Ergo,21,InputCo,500
4,Laptop Pro,780,TecnoSur,45,Silla Ergo,160,ErgoLab,80
5,Laptop Pro,780,TecnoSur,45,Escritorio,250,ErgoLab,35
6,Laptop Pro,780,TecnoSur,45,Auriculares,68,InputCo,210
7,Laptop Pro,780,TecnoSur,45,Tablet Air,390,TecnoSur,60
8,Laptop Pro,780,TecnoSur,45,iPhone 18 Pro Max,1000,Apple,250
9,Monitor 27,195,TecnoSur,120,Laptop Pro,780,TecnoSur,45
10,Monitor 27,195,TecnoSur,120,Monitor 27,195,TecnoSur,120
11,Monitor 27,195,TecnoSur,120,Teclado Mec,52,InputCo,300
12,Monitor 27,195,TecnoSur,120,Raton Ergo,21,InputCo,500
13,Monitor 27,195,TecnoSur,120,Silla Ergo,160,ErgoLab,80
14,Monitor 27,195,TecnoSur,120,Escritorio,250,ErgoLab,35
15,Monitor 27,195,TecnoSur,120,Auriculares,68,InputCo,210
16,Monitor 27,195,TecnoSur,120,Tablet Air,390,TecnoSur,60
17,Monitor 27,195,TecnoSur,120,iPhone 18 Pro Max,1000,Apple,250
18,Teclado Mec,52,InputCo,300,Laptop Pro,780,TecnoSur,45
19,Teclado Mec,52,InputCo,300,Monitor 27,195,TecnoSur,120
20,Teclado Mec,52,InputCo,300,Teclado Mec,52,InputCo,300
21,Teclado Mec,52,InputCo,300,Raton Ergo,21,InputCo,500
22,Teclado Mec,52,InputCo,300,Silla Ergo,160,ErgoLab,80
23,Teclado Mec,52,InputCo,300,Escritorio,250,ErgoLab,35
24,Teclado Mec,52,InputCo,300,Auriculares,68,InputCo,210
25,Teclado Mec,52,InputCo,300,Tablet Air,390,TecnoSur,60
26,Teclado Mec,52,InputCo,300,iPhone 18 Pro Max,1000,Apple,250
27,Raton Ergo,21,InputCo,500,Laptop Pro,780,TecnoSur,45
28,Raton Ergo,21,InputCo,500,Monitor 27,195,TecnoSur,120
29,Raton Ergo,21,InputCo,500,Teclado Mec,52,InputCo,300
30,Raton Ergo,21,InputCo,500,Raton Ergo,21,InputCo,500
31,Raton Ergo,21,InputCo,500,Silla Ergo,160,ErgoLab,80
32,Raton Ergo,21,InputCo,500,Escritorio,250,ErgoLab,35
33,Raton Ergo,21,InputCo,500,Auriculares,68,InputCo,210
34,Raton Ergo,21,InputCo,500,Tablet Air,390,TecnoSur,60
35,Raton Ergo,21,InputCo,500,iPhone 18 Pro Max,1000,Apple,250
36,Silla Ergo,160,ErgoLab,80,Laptop Pro,780,TecnoSur,45
37,Silla Ergo,160,ErgoLab,80,Monitor 27,195,TecnoSur,120
38,Silla Ergo,160,ErgoLab,80,Teclado Mec,52,InputCo,300
39,Silla Ergo,160,ErgoLab,80,Raton Ergo,21,InputCo,500
40,Silla Ergo,160,ErgoLab,80,Silla Ergo,160,ErgoLab,80
41,Silla Ergo,160,ErgoLab,80,Escritorio,250,ErgoLab,35
42,Silla Ergo,160,ErgoLab,80,Auriculares,68,InputCo,210
43,Silla Ergo,160,ErgoLab,80,Tablet Air,390,TecnoSur,60
44,Silla Ergo,160,ErgoLab,80,iPhone 18 Pro Max,1000,Apple,250
45,Escritorio,250,ErgoLab,35,Laptop Pro,780,TecnoSur,45
46,Escritorio,250,ErgoLab,35,Monitor 27,195,TecnoSur,120
47,Escritorio,250,ErgoLab,35,Teclado Mec,52,InputCo,300
48,Escritorio,250,ErgoLab,35,Raton Ergo,21,InputCo,500
49,Escritorio,250,ErgoLab,35,Silla Ergo,160,ErgoLab,80